### ISSUE TITLE
The app doesnt work anymore out of box

### ISSUE THREAD

**Issue by gautam-soni** [forcedotcom/aura-note#10]
It seems h2 db is corrupted, hence it just doesnt work. Either a new h2 db has to be re-created or we should have a way to generate one on the fly, when user doesnt pass the h2 db file to its home dir.

**Comment by mleonardsfdc** [comment]
This sample app is out-of-date and is no longer maintained. To get started with Aura, see the [Aura Open Source Developer Guide](https://github.com/forcedotcom/aura/blob/master/aura_oss.pdf).

I'm closing out this issue.
