### ISSUE TITLE
maven.auraframework.org unavailable - breaks build

### ISSUE THREAD

**Issue by hahla** [forcedotcom/aura-note#12]
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-util/7.2.0.v20101020/jetty-util-7.2.0.v20101020.pom (3 KB at 16.9 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.626 s
[INFO] Finished at: 2016-04-06T14:38:48-07:00
[INFO] Final Memory: 12M/151M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aura-note: Could not resolve dependencies for project org.auraframework.demo:aura-note:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.auraframework:aura-util:jar:0.2841: Failed to read artifact descriptor for org.auraframework:aura-util:jar:0.2841: Could not transfer artifact org.auraframework:aura-util:pom:0.2841 from/to libs-internal (http://maven.auraframework.org/libs-release): maven.auraframework.org: unknown error: Unknown host maven.auraframework.org: unknown error -> [Help 1]
[ERROR]

**Comment by patnaikshekhar** [comment]
I'm getting the same error as well.

**Comment by byao** [comment]
http://repo.auraframework.org/libs-release/ is also specified and it should be able to get artifacts from there. Please pull latest master and try again. Let me know how it goes.

**Comment by patnaikshekhar** [comment]
Still getting an error. Cloned the whole repository again and ran 
```bash 
mvn jetty:run -Pdev
```

Got the following error:

[ERROR] Failed to execute goal on project aura-note: Could not resolve dependencies for project org.auraframework.demo:aura-note:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.auraframework:aura-util:jar:0.2841: Failed to read artifact descriptor for org.auraframework:aura-util:jar:0.2841: Could not transfer artifact org.auraframework:aura-util:pom:0.2841 from/to libs-internal (http://maven.auraframework.org/libs-release): maven.auraframework.org: unknown error: Unknown host maven.auraframework.org: unknown error -> [Help 1]

**Comment by nwtek** [comment]
This is failing for me as well and i'm getting the same error"

"[ERROR] Failed to execute goal on project aura-note: Could not resolve dependencies for project org.auraframework.demo:aura-note:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.auraframework:aura-util:jar:0.2841: Failed to read artifact descriptor for org.auraframework:aura-util:jar:0.2841: Could not transfer artifact org.auraframework:aura-util:pom:0.2841 from/to libs-internal (http://maven.auraframework.org/libs-release): maven.auraframework.org: unknown error: Unknown host maven.auraframework.org: unknown error -> [Help 1]"

When visiting the URL http://maven.auraframework.org/libs-release it is a dead link.

**Comment by muthukr2** [comment]
Still getting the same error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.936 s
[INFO] Finished at: 2016-05-04T21:33:13-07:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aura-note: Could not resolve dependencies for project org.auraframework.demo:aura-note:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.auraframework:aura-util:jar:0.2841: Failed to read artifact descriptor for org.auraframework:aura-util:jar:0.2841: Could not transfer artifact org.auraframework:aura-util:pom:0.2841 from/to libs-internal (http://maven.auraframework.org/libs-release): maven.auraframework.org: nodename nor servname provided, or not known: Unknown host maven.auraframework.org: nodename nor servname provided, or not known -> [Help 1]
[ERROR]

**Comment by mleonardsfdc** [comment]
This sample app is out-of-date and is no longer maintained. To get started with Aura, see the [Aura Open Source Developer Guide](https://github.com/forcedotcom/aura/blob/master/aura_oss.pdf).

I'm closing out this issue.
