### ISSUE TITLE
Artifact download issue

### ISSUE THREAD

**Issue by vvstej** [forcedotcom/aura-note#9]
In Case you encounter this error while starting to download the artifacts and run the server
Could not resolve dependencies for project org.auraframework.demo:aura-note:jar:0.0.1-SNAPSHOT: *The following artifacts could not be resolved: org.auraframework:aura-util:jar:0.2841, org.auraframework:aura-impl:jar:0.2841, org.auraframework:aura-components:jar:0.2841, org.auraframework:aura-resources:jar:0.2841, org.auraframework:aura-impl:jar:tests:0.2841, org.auraframework:aura-util:jar:tests:0.2841: Could not find artifact org.auraframework:aura-util:jar:0.2841 in libs-internal (http://maven.auraframework.org/libs-release)*

Please make sure to configure the nexus settings in maven correctly by running the following
*mvn org.sonatype.plugins:nexus-m2settings-maven-plugin:download -DnexusUrl=https://nexus.soma.salesforce.com/nexus -DtemplateId=cfdc-default*

**Comment by vvstej** [comment]
Would be good if this can be updated in the README, since most people will encounter this issue.

**Comment by Jerrkawz** [comment]
I think there is a typo in the command. -DtemplateId=cfdc-default should be -DtemplateId=**s**fdc-default correct?

After changing that everything worked.

Prior to reading this issue I tried changing the aura version to 3343 but it caused additional problems. I filed a separate issue for that

**Comment by gordosfdc** [comment]
Actually, that is probably an issue with the repository filling up, and the
version required by aura-note accidentally being deleted. We will update
aura-note as soon as we get a chance. The OSS version of aura can only have
references to globally visible server names.

**Comment by Jerrkawz** [comment]
> Actually, that is probably an issue with the repository filling up, and the
> version required by aura-note accidentally being deleted. We will update
> aura-note as soon as we get a chance. The OSS version of aura can only have
> references to globally visible server names.

Yeah that makes sense, i was thinking that as well. Thats why I filed the other issue that updating the aura-framework-version in the pom.xml causes a null pointer exception when launching the application. It does allow everything to build properly though.

**Comment by hubsonx** [comment]
the command provided in the first post does not exactly work for me as I get:
Failed to execute goal org.sonatype.plugins:nexus-m2settings-maven-plugin:1.6.6:download (default-cli) on project aura-note: Connection failed: com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: nexus.soma.salesforce.com: Unknown host nexus.soma.salesforce.com -> [Help 1]

it's asking for some username and password, not sure what I am doing, I just want to see the demo app in action

**Comment by vishweshjoshi-tudip** [comment]
Hi All,
I am getting the same error after entering the username and password
[INFO] Connecting to: https://nexus.soma.salesforce.com/nexus
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.203 s
[INFO] Finished at: 2016-02-11T20:25:12+05:30
[INFO] Final Memory: 13M/176M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-m2settings-maven-plugin:1.6.6:download (default-cli) on project aura-note: Connection failed: com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: nexus.soma.salesforce.com: unknown error: Unknown host nexus.soma.salesforce.com: unknown error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Jerrkawz** [comment]
nexus.soma.salesforce.com is an internal salesforce repository. You have to be inside of our vpn to access it.

**Comment by vishweshjoshi-tudip** [comment]
I don't know how to get inside your vpn to access it. Please let me know the procedure for the same.

**Comment by wwwdata** [comment]
Hi, I got a problem with dependency downloads as well:

```
Downloading: http://maven.auraframework.org/libs-release/org/auraframework/aura-util/0.2841/aura-util-0.2841.pom
Downloading: http://maven.auraframework.org/libs-release/org/auraframework/aura/0.2841/aura-0.2841.pom
Downloading: http://maven.auraframework.org/libs-release/org/auraframework/aura-impl/0.2841/aura-impl-0.2841.pom
Downloading: http://maven.auraframework.org/libs-release/org/auraframework/aura-components/0.2841/aura-components-0.2841.pom
Downloading: http://maven.auraframework.org/libs-release/org/auraframework/aura-impl-expression/0.2841/aura-impl-expression-0.2841.pom
Downloading: http://maven.auraframework.org/libs-release/org/auraframework/aura-resources/0.2841/aura-resources-0.2841.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.096 s
[INFO] Finished at: 2016-03-03T15:14:03+01:00
[INFO] Final Memory: 13M/232M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aura-note: Could not resolve dependencies for project org.auraframework.demo:aura-note:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.auraframework:aura-util:jar:0.2841: Failed to read artifact descriptor for org.auraframework:aura-util:jar:0.2841: Could not transfer artifact org.auraframework:aura-util:pom:0.2841 from/to libs-internal (http://maven.auraframework.org/libs-release): maven.auraframework.org: unknown error: Unknown host maven.auraframework.org: unknown error -> [Help 1]
```

**Comment by sunqing99** [comment]
Well, even inside vpn it still did not work for me, got 404:
$ mvn org.sonatype.plugins:nexus-m2settings-maven-plugin:download -DnexusUrl=https://nexus.soma.salesforce.com/nexus -DtemplateId=sfdc-default
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Aura Framework 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- nexus-m2settings-maven-plugin:1.6.6:download (default-cli) @ aura-note ---
Username [myid]: 
Password: ****************
[INFO] Connecting to: https://nexus.soma.salesforce.com/nexus (as myid)
[INFO] Connected: Sonatype Nexus Professional 2.11.4-01
[INFO] Fetching content for templateId: sfdc-default
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.736 s
[INFO] Finished at: 2016-03-06T11:12:56-08:00
[INFO] Final Memory: 16M/242M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-m2settings-maven-plugin:1.6.6:download (default-cli) on project aura-note: Unable to fetch content for templateId: sfdc-default: Client response status: 404 -> [Help 1]

**Comment by ashutoshdikshit** [comment]
Is there an update here? I am facing the same issue and i tried configuring the nexus setting being on VPN but it didnt help.

**Comment by mleonardsfdc** [comment]
Ashutosh, It looks like you are an internal SFDC dev so I'll send you an email directly. There are better places for internal devs to get started.

This aura-note sample app is out-of-date and is no longer maintained. I'll work on updating the README to make that clearer. Sorry about the confusion!

**Comment by mleonardsfdc** [comment]
This sample app is out-of-date and is no longer maintained. To get started with Aura, see the [Aura Open Source Developer Guide](https://github.com/forcedotcom/aura/blob/master/aura_oss.pdf).

I'm closing out this issue.
